server:
  port: 8082

spring:
  application:
    name: funding
  data:
    mongodb:
      host: localhost
      prot: 27017
      database: FundingTestDB

auth:
  service:
    url: http://localhost:8080