jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    password: ${JASYPT_PASSWORD}

spring:
  application:
    name: funding
  datasource:
    url: ENC(NXC1KiDZpZkNW79dWR5WhlrWQNJmkncBjsGPb9TsTM3WfvAUxwOkGe44jYdNRL+CCKT+AURc8A/VD81ZKSZhRQEp9I6semTaxChBlJ7jsIQ=)
    username: ENC(XhGT41xwg0J9hSXkV9tPjQ==)
    password: ENC(cOWaniGDoCFEXR9v+wRBVEwsJ5Hg6vQN)
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
auth:
  service:
    url: http://auth-service.auth.svc.cluster.local:8080
pay:
  service:
    url: http://pay-service.pay.svc.cluster.local:8080

client:
  base:
    url: ENC(6glvmh8vfHd2D/ALcgqR+tXcm+DH+AZbkofU7nK5p2eE0RzPXoNE1uHTORYrT/dA)
  pay:
    url: ENC(YKKOs+X8eUEdzzngWa8yjQlR4W0uy69aKFe1AMAee9FP2nauBEWpCM6FyDXpbIprBGi7LReqA4M=)